### ISSUE TITLE
adb shell保存截图没有写权限怎么处理

### ISSUE THREAD

**Issue by mac-zhang** [Chain-Zhang/answer_ai#1]
执行命令adb shell /system/bin/screencap -p /sdcard/screenshot.png时，会报Error opening file: /sdcard/screenshot.png (Permission denied)的错误。也是魅族手机。

**Comment by Chain-Zhang** [comment]
手机的usb调试打开了没

**Comment by Chain-Zhang** [comment]
@mac-zhang 手机的usb调试打开了没

**Comment by mac-zhang** [comment]
必须要外置的sdcard？手机内置的不可以么？

**Comment by Chain-Zhang** [comment]
@mac-zhang 应该可以的。

**Comment by Chain-Zhang** [comment]
@mac-zhang 看看你手机哪些开发者的权限没开。估计是权限不够的原因吧。

**Comment by mac-zhang** [comment]
@Chain-Zhang 我试了用adb shell screencap -p | sed 's/\r$//' > screen.png这个命令直接把截图保存到电脑上，但是保存的都是无效图片，不知道你试过没？

**Comment by Chain-Zhang** [comment]
@mac-zhang  这个我没有试过，我也是第一次用adb对它并不熟悉

**Comment by mac-zhang** [comment]
@Chain-Zhang 顺便问下，你用这个答题成功率大概多少？

**Comment by Chain-Zhang** [comment]
@mac-zhang 之前的比较低，大概在70%-80%左右，刚更新了360，搜狗的搜索结果作为对比，应该会高一点。

**Comment by Chain-Zhang** [comment]
这个问题先关了，有别的问题再提新的哈
